stages:
  - test

lint-code:
  stage: test
  image: clojure:tools-deps-alpine
  when: always
  script:
    - clojure -A:kibit
    - clojure -A:eastwood

integration-tests:
  stage: test
  image: clojure:tools-deps-alpine
  when: always
  script:
    - clojure -A:test -i integration
